"""The five core schemas. Everything else in the app passes these around.

They are plain dataclasses with dict/list fields so they convert to and from
JSON with no extra libraries. Nested objects (actor, target, process) are
plain dicts on purpose: easier to read and debug for a small team.
"""
from dataclasses import dataclass, field, asdict
from typing import Any, Optional


@dataclass
class NormalizedEvent:
    event_id: str                 # our ID: evt_ + hash(provider|source|native id)
    timestamp: str                # UTC ISO-8601, e.g. 2026-09-18T14:02:11Z
    provider: str                 # "azure" (future: "aws", "gcp")
    source: str                   # entra_audit | entra_signin | m365_exchange | m365_onedrive | windows_vm | linux_vm
    event_type: str               # authentication | oauth_consent | permission_change | privileged_operation |
                                  # identity_change | mailbox_change | resource_access | process_start | file_event | other
    action: str                   # normalized verb, e.g. oauth.consent, role.assign, mail.access, process.start
    actor: dict                   # {"id", "name", "type": user|service_principal|process}
    target: dict = field(default_factory=dict)   # {"id", "name", "type"}
    asset: str = ""               # VM resource ID, mailbox, OneDrive, ...
    source_ip: str = ""
    application_id: str = ""      # always the appId (client ID), never the service principal object ID
    permissions: list = field(default_factory=list)
    process: Optional[dict] = None  # {"name","pid","path","command_line","parent_name","parent_pid","parent_path"}
    file_hash: str = ""           # SHA256 when available
    location: dict = field(default_factory=dict)  # {"city","country","lat","lon"} from sign-in logs
    details: dict = field(default_factory=dict)   # small normalized extras (role name, item count, rule params)
    raw_event_id: str = ""        # the provider's own record ID
    raw_event: dict = field(default_factory=dict)  # original record, stored verbatim, never modified

    def to_dict(self) -> dict:
        return asdict(self)

    @classmethod
    def from_dict(cls, d: dict) -> "NormalizedEvent":
        return cls(**d)


@dataclass
class DetectionSignal:
    signal_id: str
    rule_id: str
    rule_name: str
    event_id: str                 # the single event this rule fired on
    timestamp: str
    entities: dict                # correlation keys: {"user": objectId, "app": appId, "vm": resourceId}
    severity_points: int
    confidence_points: int
    summary: str                  # one factual sentence, generated by code
    detection_version: str

    def to_dict(self) -> dict:
        return asdict(self)

    @classmethod
    def from_dict(cls, d: dict) -> "DetectionSignal":
        return cls(**d)


@dataclass
class Incident:
    incident_id: str
    scenario: str                 # oauth_consent_abuse | session_misuse | privilege_escalation | vm_suspicious_activity
    title: str
    created_at: str
    first_seen: str
    last_seen: str
    correlation: dict             # how it was correlated: chain id, key, window, anchor
    affected_identities: list     # [{"id","name","roles"}]
    affected_assets: list         # [str]
    applications: list            # [{"app_id","name","publisher","verified","owner_tenant","service_principal_id"}]
    signal_ids: list
    evidence_event_ids: list      # events that triggered rules in this incident
    context_event_ids: list       # related events in the window that triggered no rule (shown, not scored)
    timeline: list                # [{"timestamp","event_id","source","label","rule_ids"}]
    severity: dict                # {"score","level","reasons":[{"factor","points","evidence"}]}
    confidence: dict              # {"score","level","reasons":[...],"limitations":[{"text","points"}]}
    recommended_actions: list     # deterministic default recommendation, e.g. ["REVOKE_OAUTH_GRANT"]
    allowed_actions: list         # the only actions the AI or analyst may choose for this incident
    action_targets: dict          # action -> target, computed by code (never by the AI)
    telemetry_available: list
    detection_version: str

    def to_dict(self) -> dict:
        return asdict(self)

    @classmethod
    def from_dict(cls, d: dict) -> "Incident":
        return cls(**d)


@dataclass
class ResponseAction:
    action_id: str
    incident_id: str
    action_type: str              # a key from response.catalog.CATALOG
    target: dict
    decision: str                 # APPROVED | REJECTED
    decided_by: str
    decided_at: str
    mode: str = ""                # LIVE | SIMULATED | "" when rejected
    status: str = ""              # SUCCEEDED | FAILED | SIMULATED | ACCEPTED_UNVERIFIED | NOT_EXECUTED
    verification: str = ""        # what we checked after the call, in plain words
    api_log: list = field(default_factory=list)    # request/response summaries (no secrets)
    rollback: dict = field(default_factory=dict)   # data needed to undo (e.g. original NSG IDs)
    note: str = ""

    def to_dict(self) -> dict:
        return asdict(self)

    @classmethod
    def from_dict(cls, d: dict) -> "ResponseAction":
        return cls(**d)


@dataclass
class AuditRecord:
    seq: int
    timestamp: str
    record_type: str              # ingest | normalize | detection | incident.created | score.severity | ...
    incident_id: Optional[str]
    actor: str                    # "system", "ai:<model>", or the analyst name
    data: Any
    app_version: str
    prev_hash: str
    hash: str = ""

    def to_dict(self) -> dict:
        return asdict(self)
